name: Laravel Gemini CI
on:
  push:
    branches:
      - master
jobs:

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Pint
        run: composer require laravel/pint --dev
      - name: Run Linting
        run: ./vendor/bin/pint

  phpstan-setup:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install PHPStan
        run: composer require phpstan/phpstan --dev
      - name: Run PHPStan Setup
        run: ./vendor/bin/phpstan analyse

  generate-tags:
    runs-on: ubuntu-latest
    needs: phpstan-setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Generate tag
        run: |
          git config --global user.email ${{ github.event.commits[0].author.email }}" 
          git config --global user.name ${{ github.actor }}
          echo "Commit: ${{ github.sha }}"
          git tag -a v$(date +%Y%m%d%H%M%S) -m "Generated tag from GitHub Action"
          git push --tags
